<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 3 Análisis exploratorio de datos (EDA) | Registros Clínicos de Insuficiencia Cardíaca</title>
  <meta name="description" content="Este libro guía al lector paso a paso en un análisis exploratorio reproducible del dataset Heart Failure Clinical Records, ofreciendo un recorrido práctico y reproducible sobre el conjunto de datos clínicos de insuficiencia cardíaca." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 3 Análisis exploratorio de datos (EDA) | Registros Clínicos de Insuficiencia Cardíaca" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Este libro guía al lector paso a paso en un análisis exploratorio reproducible del dataset Heart Failure Clinical Records, ofreciendo un recorrido práctico y reproducible sobre el conjunto de datos clínicos de insuficiencia cardíaca." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 3 Análisis exploratorio de datos (EDA) | Registros Clínicos de Insuficiencia Cardíaca" />
  
  <meta name="twitter:description" content="Este libro guía al lector paso a paso en un análisis exploratorio reproducible del dataset Heart Failure Clinical Records, ofreciendo un recorrido práctico y reproducible sobre el conjunto de datos clínicos de insuficiencia cardíaca." />
  

<meta name="author" content="Alejandro Cantillo, Joshua Hincapie y Rafael Romero." />


<meta name="date" content="2025-08-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="references.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Registros Clínicos de Insuficiencia Cardíaca</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Objetivo</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introducción</a></li>
<li class="chapter" data-level="3" data-path="02-literature.html"><a href="#an%C3%A1lisis-exploratorio-de-datos-eda"><i class="fa fa-check"></i><b>3</b> Análisis exploratorio de datos (EDA)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="análisis-exploratorio-de-datos-eda.html"><a href="análisis-exploratorio-de-datos-eda.html"><i class="fa fa-check"></i><b>3.1</b> Contexto de los datos</a></li>
<li class="chapter" data-level="3.2" data-path="02-literature.html"><a href="#extracci%C3%B3n-transformaci%C3%B3n-y-carga-etl"><i class="fa fa-check"></i><b>3.2</b> Extracción, transformación y carga (ETL)</a></li>
<li class="chapter" data-level="3.3" data-path="02-literature.html"><a href="#%C3%A1n%C3%A1lisis-de-la-variable-objetivo-death_event"><i class="fa fa-check"></i><b>3.3</b> Ánálisis de la variable objetivo: <code>DEATH_EVENT</code></a></li>
<li class="chapter" data-level="3.4" data-path="02-literature.html"><a href="#an%C3%A1lisis-de-las-variables-caracter%C3%ADsticas-independientes"><i class="fa fa-check"></i><b>3.4</b> Análisis de las variables características (independientes)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Registros Clínicos de Insuficiencia Cardíaca</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="análisis-exploratorio-de-datos-eda" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Capítulo 3</span> Análisis exploratorio de datos (EDA)<a href="#an%C3%A1lisis-exploratorio-de-datos-eda" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="contexto-de-los-datos" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Contexto de los datos<a href="análisis-exploratorio-de-datos-eda.html#contexto-de-los-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Aquí se presenta una explicación de las variables pertenecientes al conjunto de datos:</p>
<ul>
<li><p><strong>age (años):</strong> Edad del paciente.</p></li>
<li><p><strong>anaemia (lógica):</strong> Disminución de glóbulos rojos o hemoglobina.<br />
</p></li>
<li><p><strong>creatinine_phosphokinase (µg/L):</strong> Nivel de la enzima CPK en la sangre.</p></li>
<li><p><strong>diabetes (lógica):</strong> Alteración del uso de la glucosa en la sangre.</p></li>
<li><p><strong>ejection_fraction (porcentaje):</strong> Porcentaje de sangre bombeada.<br />
</p></li>
<li><p><strong>high_blood_pressure (lógica):</strong> Presión arterial elevada de forma persistente.<br />
</p></li>
<li><p><strong>platelets:</strong> Plaquetas en sangre.<br />
</p></li>
<li><p><strong>serum_creatinine (mg/dL):</strong> Nivel de creatinina en sangre.</p></li>
<li><p><strong>serum_sodium (mEq/L):</strong> Nivel de sodio en sangre.<br />
</p></li>
<li><p><strong>sex (Binario):</strong> Mujer u hombre.<br />
</p></li>
<li><p><strong>smoking (lógica):</strong> Pacientes fumadores.<br />
</p></li>
<li><p><strong>time (días):</strong> Periodo de seguimiento.</p></li>
<li><p><strong>DEATH_EVENT (lógica):</strong> Pacientes muertos o vivos (<code>Target</code>).</p></li>
</ul>
</div>
<div id="extracción-transformación-y-carga-etl" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Extracción, transformación y carga (ETL)<a href="#extracci%C3%B3n-transformaci%C3%B3n-y-carga-etl" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>Cargamos las librerías:</li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="análisis-exploratorio-de-datos-eda.html#cb1-1" tabindex="-1"></a><span class="co">#Librerias</span></span>
<span id="cb1-2"><a href="análisis-exploratorio-de-datos-eda.html#cb1-2" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-3"><a href="análisis-exploratorio-de-datos-eda.html#cb1-3" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.4     ✔ purrr     1.1.0
## ✔ forcats   1.0.0     ✔ stringr   1.5.1
## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="análisis-exploratorio-de-datos-eda.html#cb3-1" tabindex="-1"></a><span class="fu">library</span>(Amelia)</span></code></pre></div>
<pre><code>## Cargando paquete requerido: Rcpp
## ## 
## ## Amelia II: Multiple Imputation
## ## (Version 1.8.3, built: 2024-11-07)
## ## Copyright (C) 2005-2025 James Honaker, Gary King and Matthew Blackwell
## ## Refer to http://gking.harvard.edu/amelia/ for more information
## ##</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="análisis-exploratorio-de-datos-eda.html#cb5-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<ul>
<li>Cargamos el conjunto de datos:</li>
</ul>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="análisis-exploratorio-de-datos-eda.html#cb6-1" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;heart_failure_clinical_records_dataset.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 299 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (13): age, anaemia, creatinine_phosphokinase, diabetes, ejection_fractio...
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<ul>
<li>Verificamos el encabezado de los datos, sus dimensiones, nombres de columnas y estructura del dataset:</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="análisis-exploratorio-de-datos-eda.html#cb8-1" tabindex="-1"></a><span class="fu">head</span>(datos,<span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 13
##     age anaemia creatinine_phosphokinase diabetes ejection_fraction
##   &lt;dbl&gt;   &lt;dbl&gt;                    &lt;dbl&gt;    &lt;dbl&gt;             &lt;dbl&gt;
## 1    75       0                      582        0                20
## 2    55       0                     7861        0                38
## 3    65       0                      146        0                20
## 4    50       1                      111        0                20
## 5    65       1                      160        1                20
## # ℹ 8 more variables: high_blood_pressure &lt;dbl&gt;, platelets &lt;dbl&gt;,
## #   serum_creatinine &lt;dbl&gt;, serum_sodium &lt;dbl&gt;, sex &lt;dbl&gt;, smoking &lt;dbl&gt;,
## #   time &lt;dbl&gt;, DEATH_EVENT &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="análisis-exploratorio-de-datos-eda.html#cb10-1" tabindex="-1"></a><span class="fu">dim</span>(datos)</span></code></pre></div>
<pre><code>## [1] 299  13</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="análisis-exploratorio-de-datos-eda.html#cb12-1" tabindex="-1"></a><span class="fu">colnames</span>(datos)</span></code></pre></div>
<pre><code>##  [1] &quot;age&quot;                      &quot;anaemia&quot;                 
##  [3] &quot;creatinine_phosphokinase&quot; &quot;diabetes&quot;                
##  [5] &quot;ejection_fraction&quot;        &quot;high_blood_pressure&quot;     
##  [7] &quot;platelets&quot;                &quot;serum_creatinine&quot;        
##  [9] &quot;serum_sodium&quot;             &quot;sex&quot;                     
## [11] &quot;smoking&quot;                  &quot;time&quot;                    
## [13] &quot;DEATH_EVENT&quot;</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="análisis-exploratorio-de-datos-eda.html#cb14-1" tabindex="-1"></a><span class="fu">str</span>(datos)</span></code></pre></div>
<pre><code>## spc_tbl_ [299 × 13] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ age                     : num [1:299] 75 55 65 50 65 90 75 60 65 80 ...
##  $ anaemia                 : num [1:299] 0 0 0 1 1 1 1 1 0 1 ...
##  $ creatinine_phosphokinase: num [1:299] 582 7861 146 111 160 ...
##  $ diabetes                : num [1:299] 0 0 0 0 1 0 0 1 0 0 ...
##  $ ejection_fraction       : num [1:299] 20 38 20 20 20 40 15 60 65 35 ...
##  $ high_blood_pressure     : num [1:299] 1 0 0 0 0 1 0 0 0 1 ...
##  $ platelets               : num [1:299] 265000 263358 162000 210000 327000 ...
##  $ serum_creatinine        : num [1:299] 1.9 1.1 1.3 1.9 2.7 2.1 1.2 1.1 1.5 9.4 ...
##  $ serum_sodium            : num [1:299] 130 136 129 137 116 132 137 131 138 133 ...
##  $ sex                     : num [1:299] 1 1 1 1 0 1 1 1 0 1 ...
##  $ smoking                 : num [1:299] 0 0 1 0 0 1 0 1 0 1 ...
##  $ time                    : num [1:299] 4 6 7 7 8 8 10 10 10 10 ...
##  $ DEATH_EVENT             : num [1:299] 1 1 1 1 1 1 1 1 1 1 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   age = col_double(),
##   ..   anaemia = col_double(),
##   ..   creatinine_phosphokinase = col_double(),
##   ..   diabetes = col_double(),
##   ..   ejection_fraction = col_double(),
##   ..   high_blood_pressure = col_double(),
##   ..   platelets = col_double(),
##   ..   serum_creatinine = col_double(),
##   ..   serum_sodium = col_double(),
##   ..   sex = col_double(),
##   ..   smoking = col_double(),
##   ..   time = col_double(),
##   ..   DEATH_EVENT = col_double()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
<ul>
<li>Identificamos los valores <code>NA</code>:</li>
</ul>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="análisis-exploratorio-de-datos-eda.html#cb16-1" tabindex="-1"></a><span class="fu">missmap</span>(datos)</span></code></pre></div>
<pre><code>## Warning: Unknown or uninitialised column: `arguments`.
## Unknown or uninitialised column: `arguments`.</code></pre>
<pre><code>## Warning: Unknown or uninitialised column: `imputations`.</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Como se observa en el gráfico no se presentan datos faltantes en el dataset.</p>
</div>
<div id="ánálisis-de-la-variable-objetivo-death_event" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Ánálisis de la variable objetivo: <code>DEATH_EVENT</code><a href="#%C3%A1n%C3%A1lisis-de-la-variable-objetivo-death_event" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>Resumen de la variable:</li>
</ul>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="análisis-exploratorio-de-datos-eda.html#cb19-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="análisis-exploratorio-de-datos-eda.html#cb19-2" tabindex="-1"></a>  <span class="fu">count</span>(DEATH_EVENT) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="análisis-exploratorio-de-datos-eda.html#cb19-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proporcion =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   DEATH_EVENT     n proporcion
##         &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt;
## 1           0   203      0.679
## 2           1    96      0.321</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="análisis-exploratorio-de-datos-eda.html#cb21-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="análisis-exploratorio-de-datos-eda.html#cb21-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb21-3"><a href="análisis-exploratorio-de-datos-eda.html#cb21-3" tabindex="-1"></a>    <span class="at">total_registros =</span> <span class="fu">n</span>(),</span>
<span id="cb21-4"><a href="análisis-exploratorio-de-datos-eda.html#cb21-4" tabindex="-1"></a>    <span class="at">total_muertes =</span> <span class="fu">sum</span>(DEATH_EVENT <span class="sc">==</span> <span class="dv">1</span>),</span>
<span id="cb21-5"><a href="análisis-exploratorio-de-datos-eda.html#cb21-5" tabindex="-1"></a>    <span class="at">total_sobrevivientes =</span> <span class="fu">sum</span>(DEATH_EVENT <span class="sc">==</span> <span class="dv">0</span>),</span>
<span id="cb21-6"><a href="análisis-exploratorio-de-datos-eda.html#cb21-6" tabindex="-1"></a>    <span class="at">prop_muertes =</span> <span class="fu">mean</span>(DEATH_EVENT),</span>
<span id="cb21-7"><a href="análisis-exploratorio-de-datos-eda.html#cb21-7" tabindex="-1"></a>    <span class="at">prop_sobrevivientes =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">mean</span>(DEATH_EVENT))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   total_registros total_muertes total_sobrevivientes prop_muertes
##             &lt;int&gt;         &lt;int&gt;                &lt;int&gt;        &lt;dbl&gt;
## 1             299            96                  203        0.321
## # ℹ 1 more variable: prop_sobrevivientes &lt;dbl&gt;</code></pre>
<p>La variable <code>DEATH_EVENT</code> representa la mortalidad de los pacientes, indicando si el paciente murió (<code>1</code>) o no (<code>0</code>). De un total de <strong>299</strong> observaciones, el <strong>67,89%</strong> de los pacientes sobrevivieron <strong>(<span class="math inline">\(n = 203\)</span>)</strong>, mientras que el <strong>32,1%</strong> murieron <strong>(<span class="math inline">\(n = 96\)</span>)</strong>. Esta distribución de los datos está moderadamente desbalanceada, lo que sugiere que hay más casos de no fallecimiento que de fallecimiento, pero no es un desequilibrio extremo. Sin embargo, a nivel clínico la proporción del <strong>32%</strong> de defunciones es alta en comparación con la población general, lo que podría deberse a que los datos provienen de una población de alto riesgo.</p>
<ul>
<li>Diagrama de barras</li>
</ul>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="análisis-exploratorio-de-datos-eda.html#cb23-1" tabindex="-1"></a>tabla_smoking <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="análisis-exploratorio-de-datos-eda.html#cb23-2" tabindex="-1"></a>  <span class="fu">count</span>(smoking, <span class="at">name =</span> <span class="st">&quot;Pacientes&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="análisis-exploratorio-de-datos-eda.html#cb23-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb23-4"><a href="análisis-exploratorio-de-datos-eda.html#cb23-4" tabindex="-1"></a>    <span class="at">Porcentaje =</span> <span class="fu">round</span>(Pacientes <span class="sc">/</span> <span class="fu">sum</span>(Pacientes) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb23-5"><a href="análisis-exploratorio-de-datos-eda.html#cb23-5" tabindex="-1"></a>    <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Pacientes, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb23-6"><a href="análisis-exploratorio-de-datos-eda.html#cb23-6" tabindex="-1"></a></span>
<span id="cb23-7"><a href="análisis-exploratorio-de-datos-eda.html#cb23-7" tabindex="-1"></a>tabla_smoking <span class="sc">%&gt;%</span> </span>
<span id="cb23-8"><a href="análisis-exploratorio-de-datos-eda.html#cb23-8" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(smoking), <span class="at">y =</span> Pacientes)) <span class="sc">+</span></span>
<span id="cb23-9"><a href="análisis-exploratorio-de-datos-eda.html#cb23-9" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb23-10"><a href="análisis-exploratorio-de-datos-eda.html#cb23-10" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb23-11"><a href="análisis-exploratorio-de-datos-eda.html#cb23-11" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span> <span class="st">&quot;Diagrama de barras de pacientes&quot;</span>) <span class="sc">+</span> </span>
<span id="cb23-12"><a href="análisis-exploratorio-de-datos-eda.html#cb23-12" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb23-13"><a href="análisis-exploratorio-de-datos-eda.html#cb23-13" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Pacientes&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Numero de pacientes (Porcentaje)&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<ul>
<li>Gráficos</li>
</ul>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="análisis-exploratorio-de-datos-eda.html#cb24-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="análisis-exploratorio-de-datos-eda.html#cb24-2" tabindex="-1"></a>  <span class="fu">count</span>(DEATH_EVENT) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="análisis-exploratorio-de-datos-eda.html#cb24-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> n, <span class="at">fill =</span> <span class="fu">factor</span>(DEATH_EVENT))) <span class="sc">+</span></span>
<span id="cb24-4"><a href="análisis-exploratorio-de-datos-eda.html#cb24-4" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb24-5"><a href="análisis-exploratorio-de-datos-eda.html#cb24-5" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">&quot;y&quot;</span>) <span class="sc">+</span></span>
<span id="cb24-6"><a href="análisis-exploratorio-de-datos-eda.html#cb24-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;DEATH_EVENT&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Proporcion de muertes y sobrevivientes&quot;</span>) <span class="sc">+</span></span>
<span id="cb24-7"><a href="análisis-exploratorio-de-datos-eda.html#cb24-7" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;skyblue&quot;</span>, <span class="st">&quot;tomato&quot;</span>),</span>
<span id="cb24-8"><a href="análisis-exploratorio-de-datos-eda.html#cb24-8" tabindex="-1"></a>                    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;0&quot;</span> <span class="ot">=</span> <span class="st">&quot;Sobreviviente&quot;</span>, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;Muerte&quot;</span>))</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="análisis-exploratorio-de-datos-eda.html#cb25-1" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(DEATH_EVENT), <span class="at">y =</span> age)) <span class="sc">+</span></span>
<span id="cb25-2"><a href="análisis-exploratorio-de-datos-eda.html#cb25-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;orange&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb25-3"><a href="análisis-exploratorio-de-datos-eda.html#cb25-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-4"><a href="análisis-exploratorio-de-datos-eda.html#cb25-4" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Muerte (1 = si, 0 = no)&quot;</span>,</span>
<span id="cb25-5"><a href="análisis-exploratorio-de-datos-eda.html#cb25-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Edad&quot;</span>,</span>
<span id="cb25-6"><a href="análisis-exploratorio-de-datos-eda.html#cb25-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribucion de edad segun muerte&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="análisis-exploratorio-de-datos-eda.html#cb26-1" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(DEATH_EVENT), <span class="at">y =</span> ejection_fraction)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="análisis-exploratorio-de-datos-eda.html#cb26-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;tomato&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb26-3"><a href="análisis-exploratorio-de-datos-eda.html#cb26-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-4"><a href="análisis-exploratorio-de-datos-eda.html#cb26-4" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Muerte (1 = si, 0 = no)&quot;</span>,</span>
<span id="cb26-5"><a href="análisis-exploratorio-de-datos-eda.html#cb26-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Fraccion de eyeccion&quot;</span>,</span>
<span id="cb26-6"><a href="análisis-exploratorio-de-datos-eda.html#cb26-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Fraccion de eyeccion segun muerte&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
<div id="análisis-de-las-variables-características-independientes" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Análisis de las variables características (independientes)<a href="#an%C3%A1lisis-de-las-variables-caracter%C3%ADsticas-independientes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>Resumen de las variables numéricas:</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/02-literature.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
